[package]
name = "starling"
version = "2.0.0"
authors = ["Josiah Evans <koreanhalo@gmail.com>"]
description = "This tree structure is a binary merkle tree with branch compression via split indexes."
repository = "https://github.com/ChosunOne/merkle_bit"
keywords = ["binary", "merkle", "tree", "patricia"]
categories = ["data-structures", "memory-management"]
license = "MIT"
readme = "README.md"
edition = "2018"

[dev-dependencies]
bincode = "1.1.2"
rand = "0.6.5"
rocksdb = "0.11.0"
serde = {version = "1.0.88", features = ["derive"]}
criterion = "0.2.1"
afl = "0.4.3"

[dependencies]
bincode = {version = "1.1.2", optional = true}
blake2-rfc = {version = "0.2.18", optional = true}
serde = {version = "1.0.88", features = ["derive"], optional = true}
serde_json = {version = "1.0.38", optional = true}
serde_cbor = {version = "0.9.0", optional = true}
serde_yaml = {version = "0.8.8", optional = true}
serde-pickle = {version = "0.4.1", optional = true}
ron = {version = "0.4.1", optional = true}

[features]
default = []
default_tree = []
use_serde = ["default_tree", "serde"]
use_blake2b = ["blake2-rfc"]
use_bincode = ["default_tree", "serde", "bincode"]
use_json = ["default_tree", "serde", "serde_json"]
use_cbor = ["default_tree", "serde", "serde_cbor"]
use_yaml = ["default_tree", "serde", "serde_yaml"]
use_pickle = ["default_tree", "serde", "serde-pickle"]
use_ron = ["default_tree", "serde", "ron"]