[package]
name = "starling"
version = "2.1.2-beta"
authors = ["Josiah Evans <koreanhalo@gmail.com>"]
description = "This tree structure is a binary merkle tree with branch compression via split indexes."
repository = "https://github.com/ChosunOne/merkle_bit"
keywords = ["binary", "merkle", "tree", "patricia"]
categories = ["data-structures", "memory-management"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dev-dependencies]
rand = "0.6.5"
criterion = "0.2.10"

[dependencies]
bincode = { version = "1.1.2", optional = true }
blake2-rfc = { version = "0.2.18", optional = true }
serde = { version = "1.0.89", features = ["derive"], optional = true }
serde_json = { version = "1.0.39", optional = true }
serde_cbor = { version = "0.9.0", optional = true }
serde_yaml = { version = "0.8.8", optional = true }
serde-pickle = { version = "0.4.1", optional = true }
ron = { version = "0.4.2", optional = true }
groestl = { version = "0.8.0", optional = true }
openssl = { version = "0.10.19", optional = true }
tiny-keccak = { version = "1.4.2", optional = true }
hashbrown = { version = "0.1.8", optional = true }
rocksdb = { version = "0.11.0", optional = true }

[features]
default = []
default_tree = []
use_serialization = []
use_serde = ["default_tree", "serde", "use_serialization"]
use_bincode = ["default_tree", "serde", "bincode", "use_serialization"]
use_json = ["default_tree", "serde", "serde_json", "use_serialization"]
use_cbor = ["default_tree", "serde", "serde_cbor", "use_serialization"]
use_yaml = ["default_tree", "serde", "serde_yaml", "use_serialization"]
use_pickle = ["default_tree", "serde", "serde-pickle", "use_serialization"]
use_ron = ["default_tree", "serde", "ron", "use_serialization"]

use_blake2b = ["default_tree", "blake2-rfc"]
use_groestl = ["default_tree", "groestl"]
use_sha2 = ["default_tree", "openssl"]
use_sha3 = ["default_tree", "tiny-keccak"]
use_keccak = ["default_tree", "tiny-keccak"]

use_hashbrown = ["default_tree", "hashbrown"]

use_rocksdb = ["default_tree", "rocksdb"]

[[bench]]
name = "merkle_bit_benches"
harness = false