[package]
name = "starling"
version = "0.1.0"
authors = ["Josiah Evans <koreanhalo@gmail.com>"]

[build-dependencies]
protobuf-codegen = {git = "https://github.com/ChosunOne/rust-protobuf", branch = "v2.0"}
protoc = "2.0.4"
protoc-rust = {git = "https://github.com/ChosunOne/rust-protobuf", branch = "v2.0"}

[dependencies]
blake2-rfc = "0.2.18"
byteorder = "1.2.6"
bytes = "0.4.9"
cryptonight-rs = "^0.2"
hex = "0.3.2"
lazy_static = "1.1.0"
openssl = {version = "0.10.11", features = ["vendored"]}
protobuf = "2.0.4"
rand = "0.5.5"
rocksdb = "0.10.1"
rust-base58 = "0.0.4"
secp256k1 = "0.10.0"
serde = "1.0.72"
serde_derive = "1.0.72"
serde_json = "1.0.26"
tiny-keccak = "1.4.2"
uuid = {version = "0.6.5", features = ["v4"]}