[package]
name = "starling"
version = "2.5.1"
authors = ["Josiah Evans <koreanhalo@gmail.com>"]
description = "This tree structure is a binary merkle tree with branch compression via split indexes."
repository = "https://github.com/ChosunOne/merkle_bit"
keywords = ["binary", "merkle", "tree", "patricia"]
categories = ["data-structures", "memory-management"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"

[profile.bench]
debug = true
opt-level = 3

[profile.test]
debug = true

[dev-dependencies]
rand = "0.6.5"
criterion = "0.2.11"

[dependencies]
bincode = { version = "1.1.3", optional = true }
blake2-rfc = { version = "0.2.18", optional = true }
serde = { version = "1.0.90", features = ["derive"], optional = true }
serde_json = { version = "1.0.39", optional = true }
serde_cbor = { version = "0.9.0", optional = true }
serde_yaml = { version = "0.8.8", optional = true }
serde-pickle = { version = "0.5.0", optional = true }
ron = { version = "0.5.1", optional = true }
groestl = { version = "0.8.0", optional = true }
openssl = { version = "0.10.20", optional = true }
tiny-keccak = { version = "1.4.2", optional = true }
hashbrown = { version = "0.3.0", optional = true }
rocksdb = { version = "0.12.1", optional = true }
rayon = { version = "1.0.3", optional = true }
chashmap = {version = "2.2.2", optional = true }

[features]
default = []
default_tree = []
use_serialization = []
use_serde = ["default_tree", "serde", "use_serialization"]
use_bincode = ["use_serde", "bincode"]
use_json = ["use_serde", "serde_json"]
use_cbor = ["use_serde", "serde_cbor"]
use_yaml = ["use_serde", "serde_yaml"]
use_pickle = ["use_serde", "serde-pickle"]
use_ron = ["use_serde", "ron"]

use_blake2b = ["default_tree", "blake2-rfc"]
use_groestl = ["default_tree", "groestl"]
use_sha2 = ["default_tree", "openssl"]
use_sha3 = ["default_tree", "tiny-keccak"]
use_keccak = ["default_tree", "tiny-keccak"]

use_hashbrown = ["default_tree", "hashbrown"]
use_rayon = ["rayon", "chashmap"]

use_rocksdb = ["default_tree", "rocksdb"]

[[bench]]
name = "merkle_bit_benches"
harness = false

[[bench]]
name = "big_benches"
harness = false
