[package]
name = "starling"
version = "1.0.0"
authors = ["Josiah Evans <koreanhalo@gmail.com>"]
description = "This tree structure is a binary merkle tree with branch compression via split indexes."
repository = "https://github.com/ChosunOne/merkle_bit"
keywords = ["binary", "merkle", "tree", "patricia"]
license = "MIT License"

[build-dependencies]
protoc-rust = {git = "https://github.com/ChosunOne/rust-protobuf", branch = "v2.0"}

[dev-dependencies]
protobuf-codegen = {git = "https://github.com/ChosunOne/rust-protobuf", branch = "v2.0"}
protoc = "2.0.4"


blake2-rfc = "0.2.18"
protobuf = "2.0.4"
rand = "0.5.5"

[dependencies]
